services:
  postgres:
    image: postgres:16-alpine
    container_name: ms-auth-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_auth_db
      POSTGRES_USER: ms_auth_user
      POSTGRES_PASSWORD: ms_auth_pass
    ports:
      - "5432:5432"
    volumes:
      - ms_auth_pgdata:/var/lib/postgresql/data

volumes:
  ms_auth_pgdata: