services:
  postgres:
    image: postgres:16-alpine
    container_name: ms-auth-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_auth_db
      POSTGRES_USER: ms_auth_user
      POSTGRES_PASSWORD: ms_auth_pass
    ports:
      - "5432:5432"
    volumes:
      - ms_auth_pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: ms-bookings-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"    # protocolo AMQP (lo usan las apps)
      - "15672:15672"  # panel web de administración
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  ms_auth_pgdata: