events {}
http {
    server {
        listen 80;

        # ---- ms-auth ----
        location /api/auth/ {
            proxy_pass http://ms-auth:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Prefix /api/auth;
        }
        location ~ ^/api/auth/(swagger-ui|v3/api-docs) {
            rewrite ^/api/auth/(.*)$ /$1 break;
            proxy_pass http://ms-auth:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Prefix /api/auth;
        }

        # ---- ms-stadium ----
        location /api/stadiums/ {
            proxy_pass http://ms-stadiums:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Prefix /api/stadiums;
        }
        location ~ ^/api/stadiums/(swagger-ui|v3/api-docs) {
            rewrite ^/api/stadiums/(.*)$ /$1 break;
            proxy_pass http://ms-stadiums:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Prefix /api/stadiums;
        }

        # ---- ms-bookings ----
        location /api/bookings/ {
            proxy_pass http://ms-bookings:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Prefix /api/bookings;
        }
        location ~ ^/api/bookings/(swagger-ui|v3/api-docs) {
            rewrite ^/api/bookings/(.*)$ /$1 break;
            proxy_pass http://ms-bookings:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Prefix /api/bookings;
        }

        # ---- ms-notifications ----
        location /api/notifications/ {
            proxy_pass http://ms-notifications:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Prefix /api/notifications;
        }
        location ~ ^/api/notifications/(swagger-ui|v3/api-docs) {
            rewrite ^/api/notifications/(.*)$ /$1 break;
            proxy_pass http://ms-notifications:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Prefix /api/notifications;
        }
    }
}
