events {}

http {
    server {
        listen 80;

        location /api/auth/ {
            proxy_pass http://ms-auth:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Prefix /api/auth;
        }
        location ~ ^/api/auth/(swagger-ui|v3/api-docs) {
            rewrite ^/api/auth/(.*)$ /$1 break;
            proxy_pass http://ms-auth:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Prefix /api/auth;
        }
        location /api/stadiums/ {
            proxy_pass http://ms-stadium:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Prefix /api/stadiums;
        }

        location /api/bookings/ {
            proxy_pass http://ms-bookings:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Prefix /api/bookings;
        }

        location /api/notifications/ {
            proxy_pass http://ms-notifications:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Prefix /api/notifications;
        }
    }
}
